### ISSUE TITLE
Readme.MD | Development | Basic Usage | extra -- in command line syntax.

### ISSUE THREAD

**Issue by crzyhorse** [po-cheng/RequestLogParser#1]
> dotnet run --project App.RequestLogParser -- --input <path_to_input_file>

Should be dotnet run --project App.RequestLogParser --input <path_to_input_file>

**Comment by po-cheng** [comment]
The extra -- delimiter is just to ensure all the options that comes after are passed to the program itself and not the `dotnet` cli. Of course that should only happen when there are conflicting options. As for this scenario, I agree it is not necessary. 

ref: [dotnet run](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-run)
