### ISSUE TITLE
Output doesn't consider the status of the request. 

### ISSUE THREAD

**Issue by crzyhorse** [po-cheng/RequestLogParser#2]
Per the requirements, output file should have;

Number of successful resource accesses by URI. Only “GET” accesses to each URI are to be
counted. Only requests which resulted in the HTTP reply code 200 (“OK”) are to be counted.

From what I see, all statuses are returned.

**Comment by po-cheng** [comment]
Sorry, I took the filter out for testing things and forgot to add it back in. This issue has been fixed.
